version: '3.9'

services:
  backend:
    build: ./backend
    image: pocketbase-backend
    container_name: pocketbase
    networks:
      - internal
    volumes:
      - pb_data:/pb/pb_data
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: react-frontend
    container_name: react
    ports:
      - "1234:1235"
    networks:
      - internal
      - public
    environment:
      - VITE_POCKETBASE=http://pocketbase-backend:8090
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  public:
    driver: bridge

volumes:
  pb_data:
