version: '3'
services:
  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "1234:1235"
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"