version: '3.9'

services:
  backend:
    build: ./backend
    image: pocketbase-backend
    container_name: pocketbase
    networks:
      - internal
    ports:
      - "8090:8090"
    volumes:
      - pocketbase-data:/pb/pb_data

  frontend:
    build: ./frontend
    image: react-frontend
    container_name: react
    ports:
      - "1234:1235"
    networks:
      - internal
      - public

networks:
  internal:
    driver: bridge
  public:
    driver: bridge

volumes:
  pocketbase-data:
